# 应用基础配置
app:
  name: "app"
  env: "dev"

# HTTP 服务配置
http_server:
  addr: ":8888"

# 业务私有配置
biz:
  jwt_secret: "walk_jwt_secret"
  aes_secret: "walk_aes_secret"
  wechat_app_id: ""
  wechat_secret: ""
  front_end_url: ""
  expired_date: "2025-12-31 23:59:59"
  open_date: "2025-01-01 00:00:00"
  submit_date: "2025-12-01 23:59:59"
  max_team_size: 6
  min_submit_size: 4

log:
  level: 4

resty:
  timeout: "5s"

mid_cors:
  allow_origins:
    - "*"

# 注意：项目读取的是 db，不是 mysql
db:
  host: "localhost"
  port: 3306
  username: "root"
  password: "coppklmja!BWZ"
  database: "walk_server"

redis:
  addrs:
    - "127.0.0.1:6379"
  db: 0
  password: ""

lock:
  redis: "redis"

feishu:
  enable: false
  notice_webhook: ""
  notice_secret: ""

session:
  driver: "memory"
  name: "session"
  secret: "secert"
  redis: ""
