// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newCheckin(db *gorm.DB, opts ...gen.DOOption) checkin {
	_checkin := checkin{}

	_checkin.checkinDo.UseDB(db, opts...)
	_checkin.checkinDo.UseModel(&model.Checkin{})

	tableName := _checkin.checkinDo.TableName()
	_checkin.ALL = field.NewAsterisk(tableName)
	_checkin.ID = field.NewInt64(tableName, "id")
	_checkin.AdminID = field.NewInt64(tableName, "admin_id")
	_checkin.TeamID = field.NewInt64(tableName, "team_id")
	_checkin.PointName = field.NewString(tableName, "point_name")
	_checkin.RouteName = field.NewString(tableName, "route_name")
	_checkin.Time = field.NewTime(tableName, "time")
	_checkin.UpdatedAt = field.NewTime(tableName, "updated_at")
	_checkin.CreatedAt = field.NewTime(tableName, "created_at")

	_checkin.fillFieldMap()

	return _checkin
}

type checkin struct {
	checkinDo checkinDo

	ALL       field.Asterisk
	ID        field.Int64
	AdminID   field.Int64  // 签到管理员ID
	TeamID    field.Int64  // 队伍ID
	PointName field.String // 签到点位ID
	RouteName field.String // 路线id
	Time      field.Time   // 签到时间
	UpdatedAt field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (c checkin) Table(newTableName string) *checkin {
	c.checkinDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c checkin) As(alias string) *checkin {
	c.checkinDo.DO = *(c.checkinDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *checkin) updateTableName(table string) *checkin {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.AdminID = field.NewInt64(table, "admin_id")
	c.TeamID = field.NewInt64(table, "team_id")
	c.PointName = field.NewString(table, "point_name")
	c.RouteName = field.NewString(table, "route_name")
	c.Time = field.NewTime(table, "time")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *checkin) WithContext(ctx context.Context) ICheckinDo { return c.checkinDo.WithContext(ctx) }

func (c checkin) TableName() string { return c.checkinDo.TableName() }

func (c checkin) Alias() string { return c.checkinDo.Alias() }

func (c checkin) Columns(cols ...field.Expr) gen.Columns { return c.checkinDo.Columns(cols...) }

func (c *checkin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *checkin) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["admin_id"] = c.AdminID
	c.fieldMap["team_id"] = c.TeamID
	c.fieldMap["point_name"] = c.PointName
	c.fieldMap["route_name"] = c.RouteName
	c.fieldMap["time"] = c.Time
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c checkin) clone(db *gorm.DB) checkin {
	c.checkinDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c checkin) replaceDB(db *gorm.DB) checkin {
	c.checkinDo.ReplaceDB(db)
	return c
}

type checkinDo struct{ gen.DO }

type ICheckinDo interface {
	gen.SubQuery
	Debug() ICheckinDo
	WithContext(ctx context.Context) ICheckinDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICheckinDo
	WriteDB() ICheckinDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICheckinDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICheckinDo
	Not(conds ...gen.Condition) ICheckinDo
	Or(conds ...gen.Condition) ICheckinDo
	Select(conds ...field.Expr) ICheckinDo
	Where(conds ...gen.Condition) ICheckinDo
	Order(conds ...field.Expr) ICheckinDo
	Distinct(cols ...field.Expr) ICheckinDo
	Omit(cols ...field.Expr) ICheckinDo
	Join(table schema.Tabler, on ...field.Expr) ICheckinDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICheckinDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICheckinDo
	Group(cols ...field.Expr) ICheckinDo
	Having(conds ...gen.Condition) ICheckinDo
	Limit(limit int) ICheckinDo
	Offset(offset int) ICheckinDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICheckinDo
	Unscoped() ICheckinDo
	Create(values ...*model.Checkin) error
	CreateInBatches(values []*model.Checkin, batchSize int) error
	Save(values ...*model.Checkin) error
	First() (*model.Checkin, error)
	Take() (*model.Checkin, error)
	Last() (*model.Checkin, error)
	Find() ([]*model.Checkin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Checkin, err error)
	FindInBatches(result *[]*model.Checkin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Checkin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICheckinDo
	Assign(attrs ...field.AssignExpr) ICheckinDo
	Joins(fields ...field.RelationField) ICheckinDo
	Preload(fields ...field.RelationField) ICheckinDo
	FirstOrInit() (*model.Checkin, error)
	FirstOrCreate() (*model.Checkin, error)
	FindByPage(offset int, limit int) (result []*model.Checkin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICheckinDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c checkinDo) Debug() ICheckinDo {
	return c.withDO(c.DO.Debug())
}

func (c checkinDo) WithContext(ctx context.Context) ICheckinDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c checkinDo) ReadDB() ICheckinDo {
	return c.Clauses(dbresolver.Read)
}

func (c checkinDo) WriteDB() ICheckinDo {
	return c.Clauses(dbresolver.Write)
}

func (c checkinDo) Session(config *gorm.Session) ICheckinDo {
	return c.withDO(c.DO.Session(config))
}

func (c checkinDo) Clauses(conds ...clause.Expression) ICheckinDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c checkinDo) Returning(value interface{}, columns ...string) ICheckinDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c checkinDo) Not(conds ...gen.Condition) ICheckinDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c checkinDo) Or(conds ...gen.Condition) ICheckinDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c checkinDo) Select(conds ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c checkinDo) Where(conds ...gen.Condition) ICheckinDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c checkinDo) Order(conds ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c checkinDo) Distinct(cols ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c checkinDo) Omit(cols ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c checkinDo) Join(table schema.Tabler, on ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c checkinDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c checkinDo) RightJoin(table schema.Tabler, on ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c checkinDo) Group(cols ...field.Expr) ICheckinDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c checkinDo) Having(conds ...gen.Condition) ICheckinDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c checkinDo) Limit(limit int) ICheckinDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c checkinDo) Offset(offset int) ICheckinDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c checkinDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICheckinDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c checkinDo) Unscoped() ICheckinDo {
	return c.withDO(c.DO.Unscoped())
}

func (c checkinDo) Create(values ...*model.Checkin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c checkinDo) CreateInBatches(values []*model.Checkin, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c checkinDo) Save(values ...*model.Checkin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c checkinDo) First() (*model.Checkin, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Take() (*model.Checkin, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Last() (*model.Checkin, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) Find() ([]*model.Checkin, error) {
	result, err := c.DO.Find()
	return result.([]*model.Checkin), err
}

func (c checkinDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Checkin, err error) {
	buf := make([]*model.Checkin, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c checkinDo) FindInBatches(result *[]*model.Checkin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c checkinDo) Attrs(attrs ...field.AssignExpr) ICheckinDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c checkinDo) Assign(attrs ...field.AssignExpr) ICheckinDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c checkinDo) Joins(fields ...field.RelationField) ICheckinDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c checkinDo) Preload(fields ...field.RelationField) ICheckinDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c checkinDo) FirstOrInit() (*model.Checkin, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) FirstOrCreate() (*model.Checkin, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Checkin), nil
	}
}

func (c checkinDo) FindByPage(offset int, limit int) (result []*model.Checkin, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c checkinDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c checkinDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c checkinDo) Delete(models ...*model.Checkin) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *checkinDo) withDO(do gen.Dao) *checkinDo {
	c.DO = *do.(*gen.DO)
	return c
}
