// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Admin            *admin
	Checkin          *checkin
	People           *people
	Point            *point
	Route            *route
	RouteEdge        *routeEdge
	Team             *team
	WrongRouteRecord *wrongRouteRecord
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	Checkin = &Q.Checkin
	People = &Q.People
	Point = &Q.Point
	Route = &Q.Route
	RouteEdge = &Q.RouteEdge
	Team = &Q.Team
	WrongRouteRecord = &Q.WrongRouteRecord
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Admin:            newAdmin(db, opts...),
		Checkin:          newCheckin(db, opts...),
		People:           newPeople(db, opts...),
		Point:            newPoint(db, opts...),
		Route:            newRoute(db, opts...),
		RouteEdge:        newRouteEdge(db, opts...),
		Team:             newTeam(db, opts...),
		WrongRouteRecord: newWrongRouteRecord(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin            admin
	Checkin          checkin
	People           people
	Point            point
	Route            route
	RouteEdge        routeEdge
	Team             team
	WrongRouteRecord wrongRouteRecord
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Admin:            q.Admin.clone(db),
		Checkin:          q.Checkin.clone(db),
		People:           q.People.clone(db),
		Point:            q.Point.clone(db),
		Route:            q.Route.clone(db),
		RouteEdge:        q.RouteEdge.clone(db),
		Team:             q.Team.clone(db),
		WrongRouteRecord: q.WrongRouteRecord.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Admin:            q.Admin.replaceDB(db),
		Checkin:          q.Checkin.replaceDB(db),
		People:           q.People.replaceDB(db),
		Point:            q.Point.replaceDB(db),
		Route:            q.Route.replaceDB(db),
		RouteEdge:        q.RouteEdge.replaceDB(db),
		Team:             q.Team.replaceDB(db),
		WrongRouteRecord: q.WrongRouteRecord.replaceDB(db),
	}
}

type queryCtx struct {
	Admin            IAdminDo
	Checkin          ICheckinDo
	People           IPeopleDo
	Point            IPointDo
	Route            IRouteDo
	RouteEdge        IRouteEdgeDo
	Team             ITeamDo
	WrongRouteRecord IWrongRouteRecordDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:            q.Admin.WithContext(ctx),
		Checkin:          q.Checkin.WithContext(ctx),
		People:           q.People.WithContext(ctx),
		Point:            q.Point.WithContext(ctx),
		Route:            q.Route.WithContext(ctx),
		RouteEdge:        q.RouteEdge.WithContext(ctx),
		Team:             q.Team.WithContext(ctx),
		WrongRouteRecord: q.WrongRouteRecord.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
