// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newPeople(db *gorm.DB, opts ...gen.DOOption) people {
	_people := people{}

	_people.peopleDo.UseDB(db, opts...)
	_people.peopleDo.UseModel(&model.People{})

	tableName := _people.peopleDo.TableName()
	_people.ALL = field.NewAsterisk(tableName)
	_people.ID = field.NewInt64(tableName, "id")
	_people.OpenID = field.NewString(tableName, "open_id")
	_people.Name = field.NewString(tableName, "name")
	_people.Gender = field.NewInt8(tableName, "gender")
	_people.StuID = field.NewString(tableName, "stu_id")
	_people.Campus = field.NewString(tableName, "campus")
	_people.Identity = field.NewString(tableName, "identity")
	_people.Role = field.NewString(tableName, "role")
	_people.Qq = field.NewString(tableName, "qq")
	_people.Wechat = field.NewString(tableName, "wechat")
	_people.College = field.NewString(tableName, "college")
	_people.Tel = field.NewString(tableName, "tel")
	_people.CreatedOp = field.NewInt8(tableName, "created_op")
	_people.JoinOp = field.NewInt8(tableName, "join_op")
	_people.TeamID = field.NewInt64(tableName, "team_id")
	_people.Type = field.NewString(tableName, "type")
	_people.WalkStatus = field.NewString(tableName, "walk_status")
	_people.UpdatedAt = field.NewTime(tableName, "updated_at")
	_people.CreatedAt = field.NewTime(tableName, "created_at")

	_people.fillFieldMap()

	return _people
}

type people struct {
	peopleDo peopleDo

	ALL        field.Asterisk
	ID         field.Int64
	OpenID     field.String // 微信OpenID
	Name       field.String // 姓名
	Gender     field.Int8   // 性别(1男,2女)
	StuID      field.String // 学号
	Campus     field.String // 校区(zh朝晖,pf屏峰,mgs莫干山)
	Identity   field.String // 身份证号
	Role       field.String // 队伍中身份(unbind未绑定,menber成员,captain队长)
	Qq         field.String // QQ号
	Wechat     field.String // 微信号
	College    field.String // 学院
	Tel        field.String // 联系电话
	CreatedOp  field.Int8   // 剩余创建团队次数
	JoinOp     field.Int8   // 剩余加入团队次数
	TeamID     field.Int64  // 所属团队ID
	Type       field.String // 人员类型(alumni校友，student学生，staff教职工)
	WalkStatus field.String // 活动状态(未开始,待出发,已放弃,进行中,已下撤,已违规,已完成)
	UpdatedAt  field.Time
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (p people) Table(newTableName string) *people {
	p.peopleDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p people) As(alias string) *people {
	p.peopleDo.DO = *(p.peopleDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *people) updateTableName(table string) *people {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.OpenID = field.NewString(table, "open_id")
	p.Name = field.NewString(table, "name")
	p.Gender = field.NewInt8(table, "gender")
	p.StuID = field.NewString(table, "stu_id")
	p.Campus = field.NewString(table, "campus")
	p.Identity = field.NewString(table, "identity")
	p.Role = field.NewString(table, "role")
	p.Qq = field.NewString(table, "qq")
	p.Wechat = field.NewString(table, "wechat")
	p.College = field.NewString(table, "college")
	p.Tel = field.NewString(table, "tel")
	p.CreatedOp = field.NewInt8(table, "created_op")
	p.JoinOp = field.NewInt8(table, "join_op")
	p.TeamID = field.NewInt64(table, "team_id")
	p.Type = field.NewString(table, "type")
	p.WalkStatus = field.NewString(table, "walk_status")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *people) WithContext(ctx context.Context) IPeopleDo { return p.peopleDo.WithContext(ctx) }

func (p people) TableName() string { return p.peopleDo.TableName() }

func (p people) Alias() string { return p.peopleDo.Alias() }

func (p people) Columns(cols ...field.Expr) gen.Columns { return p.peopleDo.Columns(cols...) }

func (p *people) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *people) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 19)
	p.fieldMap["id"] = p.ID
	p.fieldMap["open_id"] = p.OpenID
	p.fieldMap["name"] = p.Name
	p.fieldMap["gender"] = p.Gender
	p.fieldMap["stu_id"] = p.StuID
	p.fieldMap["campus"] = p.Campus
	p.fieldMap["identity"] = p.Identity
	p.fieldMap["role"] = p.Role
	p.fieldMap["qq"] = p.Qq
	p.fieldMap["wechat"] = p.Wechat
	p.fieldMap["college"] = p.College
	p.fieldMap["tel"] = p.Tel
	p.fieldMap["created_op"] = p.CreatedOp
	p.fieldMap["join_op"] = p.JoinOp
	p.fieldMap["team_id"] = p.TeamID
	p.fieldMap["type"] = p.Type
	p.fieldMap["walk_status"] = p.WalkStatus
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p people) clone(db *gorm.DB) people {
	p.peopleDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p people) replaceDB(db *gorm.DB) people {
	p.peopleDo.ReplaceDB(db)
	return p
}

type peopleDo struct{ gen.DO }

type IPeopleDo interface {
	gen.SubQuery
	Debug() IPeopleDo
	WithContext(ctx context.Context) IPeopleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPeopleDo
	WriteDB() IPeopleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPeopleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPeopleDo
	Not(conds ...gen.Condition) IPeopleDo
	Or(conds ...gen.Condition) IPeopleDo
	Select(conds ...field.Expr) IPeopleDo
	Where(conds ...gen.Condition) IPeopleDo
	Order(conds ...field.Expr) IPeopleDo
	Distinct(cols ...field.Expr) IPeopleDo
	Omit(cols ...field.Expr) IPeopleDo
	Join(table schema.Tabler, on ...field.Expr) IPeopleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPeopleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPeopleDo
	Group(cols ...field.Expr) IPeopleDo
	Having(conds ...gen.Condition) IPeopleDo
	Limit(limit int) IPeopleDo
	Offset(offset int) IPeopleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPeopleDo
	Unscoped() IPeopleDo
	Create(values ...*model.People) error
	CreateInBatches(values []*model.People, batchSize int) error
	Save(values ...*model.People) error
	First() (*model.People, error)
	Take() (*model.People, error)
	Last() (*model.People, error)
	Find() ([]*model.People, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.People, err error)
	FindInBatches(result *[]*model.People, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.People) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPeopleDo
	Assign(attrs ...field.AssignExpr) IPeopleDo
	Joins(fields ...field.RelationField) IPeopleDo
	Preload(fields ...field.RelationField) IPeopleDo
	FirstOrInit() (*model.People, error)
	FirstOrCreate() (*model.People, error)
	FindByPage(offset int, limit int) (result []*model.People, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPeopleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p peopleDo) Debug() IPeopleDo {
	return p.withDO(p.DO.Debug())
}

func (p peopleDo) WithContext(ctx context.Context) IPeopleDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p peopleDo) ReadDB() IPeopleDo {
	return p.Clauses(dbresolver.Read)
}

func (p peopleDo) WriteDB() IPeopleDo {
	return p.Clauses(dbresolver.Write)
}

func (p peopleDo) Session(config *gorm.Session) IPeopleDo {
	return p.withDO(p.DO.Session(config))
}

func (p peopleDo) Clauses(conds ...clause.Expression) IPeopleDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p peopleDo) Returning(value interface{}, columns ...string) IPeopleDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p peopleDo) Not(conds ...gen.Condition) IPeopleDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p peopleDo) Or(conds ...gen.Condition) IPeopleDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p peopleDo) Select(conds ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p peopleDo) Where(conds ...gen.Condition) IPeopleDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p peopleDo) Order(conds ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p peopleDo) Distinct(cols ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p peopleDo) Omit(cols ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p peopleDo) Join(table schema.Tabler, on ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p peopleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p peopleDo) RightJoin(table schema.Tabler, on ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p peopleDo) Group(cols ...field.Expr) IPeopleDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p peopleDo) Having(conds ...gen.Condition) IPeopleDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p peopleDo) Limit(limit int) IPeopleDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p peopleDo) Offset(offset int) IPeopleDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p peopleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPeopleDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p peopleDo) Unscoped() IPeopleDo {
	return p.withDO(p.DO.Unscoped())
}

func (p peopleDo) Create(values ...*model.People) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p peopleDo) CreateInBatches(values []*model.People, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p peopleDo) Save(values ...*model.People) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p peopleDo) First() (*model.People, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.People), nil
	}
}

func (p peopleDo) Take() (*model.People, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.People), nil
	}
}

func (p peopleDo) Last() (*model.People, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.People), nil
	}
}

func (p peopleDo) Find() ([]*model.People, error) {
	result, err := p.DO.Find()
	return result.([]*model.People), err
}

func (p peopleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.People, err error) {
	buf := make([]*model.People, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p peopleDo) FindInBatches(result *[]*model.People, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p peopleDo) Attrs(attrs ...field.AssignExpr) IPeopleDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p peopleDo) Assign(attrs ...field.AssignExpr) IPeopleDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p peopleDo) Joins(fields ...field.RelationField) IPeopleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p peopleDo) Preload(fields ...field.RelationField) IPeopleDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p peopleDo) FirstOrInit() (*model.People, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.People), nil
	}
}

func (p peopleDo) FirstOrCreate() (*model.People, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.People), nil
	}
}

func (p peopleDo) FindByPage(offset int, limit int) (result []*model.People, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p peopleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p peopleDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p peopleDo) Delete(models ...*model.People) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *peopleDo) withDO(do gen.Dao) *peopleDo {
	p.DO = *do.(*gen.DO)
	return p
}
