// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newRouteEdge(db *gorm.DB, opts ...gen.DOOption) routeEdge {
	_routeEdge := routeEdge{}

	_routeEdge.routeEdgeDo.UseDB(db, opts...)
	_routeEdge.routeEdgeDo.UseModel(&model.RouteEdge{})

	tableName := _routeEdge.routeEdgeDo.TableName()
	_routeEdge.ALL = field.NewAsterisk(tableName)
	_routeEdge.ID = field.NewInt64(tableName, "id")
	_routeEdge.PrevPointName = field.NewString(tableName, "prev_point_name")
	_routeEdge.PointName = field.NewString(tableName, "point_name")
	_routeEdge.RouteName = field.NewString(tableName, "route_name")
	_routeEdge.SeqOrder = field.NewInt8(tableName, "seq_order")
	_routeEdge.UpdatedAt = field.NewTime(tableName, "updated_at")
	_routeEdge.CreatedAt = field.NewTime(tableName, "created_at")

	_routeEdge.fillFieldMap()

	return _routeEdge
}

type routeEdge struct {
	routeEdgeDo routeEdgeDo

	ALL           field.Asterisk
	ID            field.Int64
	PrevPointName field.String // 前一个点位ID
	PointName     field.String // 当前点位ID
	RouteName     field.String // 点位所属路线名称
	SeqOrder      field.Int8   // 点位在路线中的顺序
	UpdatedAt     field.Time
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (r routeEdge) Table(newTableName string) *routeEdge {
	r.routeEdgeDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r routeEdge) As(alias string) *routeEdge {
	r.routeEdgeDo.DO = *(r.routeEdgeDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *routeEdge) updateTableName(table string) *routeEdge {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.PrevPointName = field.NewString(table, "prev_point_name")
	r.PointName = field.NewString(table, "point_name")
	r.RouteName = field.NewString(table, "route_name")
	r.SeqOrder = field.NewInt8(table, "seq_order")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *routeEdge) WithContext(ctx context.Context) IRouteEdgeDo {
	return r.routeEdgeDo.WithContext(ctx)
}

func (r routeEdge) TableName() string { return r.routeEdgeDo.TableName() }

func (r routeEdge) Alias() string { return r.routeEdgeDo.Alias() }

func (r routeEdge) Columns(cols ...field.Expr) gen.Columns { return r.routeEdgeDo.Columns(cols...) }

func (r *routeEdge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *routeEdge) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["prev_point_name"] = r.PrevPointName
	r.fieldMap["point_name"] = r.PointName
	r.fieldMap["route_name"] = r.RouteName
	r.fieldMap["seq_order"] = r.SeqOrder
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r routeEdge) clone(db *gorm.DB) routeEdge {
	r.routeEdgeDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r routeEdge) replaceDB(db *gorm.DB) routeEdge {
	r.routeEdgeDo.ReplaceDB(db)
	return r
}

type routeEdgeDo struct{ gen.DO }

type IRouteEdgeDo interface {
	gen.SubQuery
	Debug() IRouteEdgeDo
	WithContext(ctx context.Context) IRouteEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRouteEdgeDo
	WriteDB() IRouteEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRouteEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRouteEdgeDo
	Not(conds ...gen.Condition) IRouteEdgeDo
	Or(conds ...gen.Condition) IRouteEdgeDo
	Select(conds ...field.Expr) IRouteEdgeDo
	Where(conds ...gen.Condition) IRouteEdgeDo
	Order(conds ...field.Expr) IRouteEdgeDo
	Distinct(cols ...field.Expr) IRouteEdgeDo
	Omit(cols ...field.Expr) IRouteEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IRouteEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRouteEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRouteEdgeDo
	Group(cols ...field.Expr) IRouteEdgeDo
	Having(conds ...gen.Condition) IRouteEdgeDo
	Limit(limit int) IRouteEdgeDo
	Offset(offset int) IRouteEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRouteEdgeDo
	Unscoped() IRouteEdgeDo
	Create(values ...*model.RouteEdge) error
	CreateInBatches(values []*model.RouteEdge, batchSize int) error
	Save(values ...*model.RouteEdge) error
	First() (*model.RouteEdge, error)
	Take() (*model.RouteEdge, error)
	Last() (*model.RouteEdge, error)
	Find() ([]*model.RouteEdge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouteEdge, err error)
	FindInBatches(result *[]*model.RouteEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RouteEdge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRouteEdgeDo
	Assign(attrs ...field.AssignExpr) IRouteEdgeDo
	Joins(fields ...field.RelationField) IRouteEdgeDo
	Preload(fields ...field.RelationField) IRouteEdgeDo
	FirstOrInit() (*model.RouteEdge, error)
	FirstOrCreate() (*model.RouteEdge, error)
	FindByPage(offset int, limit int) (result []*model.RouteEdge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRouteEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r routeEdgeDo) Debug() IRouteEdgeDo {
	return r.withDO(r.DO.Debug())
}

func (r routeEdgeDo) WithContext(ctx context.Context) IRouteEdgeDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r routeEdgeDo) ReadDB() IRouteEdgeDo {
	return r.Clauses(dbresolver.Read)
}

func (r routeEdgeDo) WriteDB() IRouteEdgeDo {
	return r.Clauses(dbresolver.Write)
}

func (r routeEdgeDo) Session(config *gorm.Session) IRouteEdgeDo {
	return r.withDO(r.DO.Session(config))
}

func (r routeEdgeDo) Clauses(conds ...clause.Expression) IRouteEdgeDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r routeEdgeDo) Returning(value interface{}, columns ...string) IRouteEdgeDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r routeEdgeDo) Not(conds ...gen.Condition) IRouteEdgeDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r routeEdgeDo) Or(conds ...gen.Condition) IRouteEdgeDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r routeEdgeDo) Select(conds ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r routeEdgeDo) Where(conds ...gen.Condition) IRouteEdgeDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r routeEdgeDo) Order(conds ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r routeEdgeDo) Distinct(cols ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r routeEdgeDo) Omit(cols ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r routeEdgeDo) Join(table schema.Tabler, on ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r routeEdgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r routeEdgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r routeEdgeDo) Group(cols ...field.Expr) IRouteEdgeDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r routeEdgeDo) Having(conds ...gen.Condition) IRouteEdgeDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r routeEdgeDo) Limit(limit int) IRouteEdgeDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r routeEdgeDo) Offset(offset int) IRouteEdgeDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r routeEdgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRouteEdgeDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r routeEdgeDo) Unscoped() IRouteEdgeDo {
	return r.withDO(r.DO.Unscoped())
}

func (r routeEdgeDo) Create(values ...*model.RouteEdge) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r routeEdgeDo) CreateInBatches(values []*model.RouteEdge, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r routeEdgeDo) Save(values ...*model.RouteEdge) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r routeEdgeDo) First() (*model.RouteEdge, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteEdge), nil
	}
}

func (r routeEdgeDo) Take() (*model.RouteEdge, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteEdge), nil
	}
}

func (r routeEdgeDo) Last() (*model.RouteEdge, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteEdge), nil
	}
}

func (r routeEdgeDo) Find() ([]*model.RouteEdge, error) {
	result, err := r.DO.Find()
	return result.([]*model.RouteEdge), err
}

func (r routeEdgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouteEdge, err error) {
	buf := make([]*model.RouteEdge, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r routeEdgeDo) FindInBatches(result *[]*model.RouteEdge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r routeEdgeDo) Attrs(attrs ...field.AssignExpr) IRouteEdgeDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r routeEdgeDo) Assign(attrs ...field.AssignExpr) IRouteEdgeDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r routeEdgeDo) Joins(fields ...field.RelationField) IRouteEdgeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r routeEdgeDo) Preload(fields ...field.RelationField) IRouteEdgeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r routeEdgeDo) FirstOrInit() (*model.RouteEdge, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteEdge), nil
	}
}

func (r routeEdgeDo) FirstOrCreate() (*model.RouteEdge, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteEdge), nil
	}
}

func (r routeEdgeDo) FindByPage(offset int, limit int) (result []*model.RouteEdge, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r routeEdgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r routeEdgeDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r routeEdgeDo) Delete(models ...*model.RouteEdge) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *routeEdgeDo) withDO(do gen.Dao) *routeEdgeDo {
	r.DO = *do.(*gen.DO)
	return r
}
