// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newWrongRouteRecord(db *gorm.DB, opts ...gen.DOOption) wrongRouteRecord {
	_wrongRouteRecord := wrongRouteRecord{}

	_wrongRouteRecord.wrongRouteRecordDo.UseDB(db, opts...)
	_wrongRouteRecord.wrongRouteRecordDo.UseModel(&model.WrongRouteRecord{})

	tableName := _wrongRouteRecord.wrongRouteRecordDo.TableName()
	_wrongRouteRecord.ALL = field.NewAsterisk(tableName)
	_wrongRouteRecord.ID = field.NewInt64(tableName, "id")
	_wrongRouteRecord.TeamID = field.NewInt64(tableName, "team_id")
	_wrongRouteRecord.RouteName = field.NewString(tableName, "route_name")
	_wrongRouteRecord.WrongRouteName = field.NewString(tableName, "wrong_route_name")
	_wrongRouteRecord.AdminID = field.NewInt64(tableName, "admin_id")
	_wrongRouteRecord.UpdatedAt = field.NewTime(tableName, "updated_at")
	_wrongRouteRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_wrongRouteRecord.fillFieldMap()

	return _wrongRouteRecord
}

type wrongRouteRecord struct {
	wrongRouteRecordDo wrongRouteRecordDo

	ALL            field.Asterisk
	ID             field.Int64
	TeamID         field.Int64  // 队伍ID
	RouteName      field.String // 原正确路线id如pf-half
	WrongRouteName field.String // 错走的路线id
	AdminID        field.Int64  // 记录该情况的管理员ID
	UpdatedAt      field.Time
	CreatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (w wrongRouteRecord) Table(newTableName string) *wrongRouteRecord {
	w.wrongRouteRecordDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wrongRouteRecord) As(alias string) *wrongRouteRecord {
	w.wrongRouteRecordDo.DO = *(w.wrongRouteRecordDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wrongRouteRecord) updateTableName(table string) *wrongRouteRecord {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.TeamID = field.NewInt64(table, "team_id")
	w.RouteName = field.NewString(table, "route_name")
	w.WrongRouteName = field.NewString(table, "wrong_route_name")
	w.AdminID = field.NewInt64(table, "admin_id")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.CreatedAt = field.NewTime(table, "created_at")

	w.fillFieldMap()

	return w
}

func (w *wrongRouteRecord) WithContext(ctx context.Context) IWrongRouteRecordDo {
	return w.wrongRouteRecordDo.WithContext(ctx)
}

func (w wrongRouteRecord) TableName() string { return w.wrongRouteRecordDo.TableName() }

func (w wrongRouteRecord) Alias() string { return w.wrongRouteRecordDo.Alias() }

func (w wrongRouteRecord) Columns(cols ...field.Expr) gen.Columns {
	return w.wrongRouteRecordDo.Columns(cols...)
}

func (w *wrongRouteRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wrongRouteRecord) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["id"] = w.ID
	w.fieldMap["team_id"] = w.TeamID
	w.fieldMap["route_name"] = w.RouteName
	w.fieldMap["wrong_route_name"] = w.WrongRouteName
	w.fieldMap["admin_id"] = w.AdminID
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["created_at"] = w.CreatedAt
}

func (w wrongRouteRecord) clone(db *gorm.DB) wrongRouteRecord {
	w.wrongRouteRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wrongRouteRecord) replaceDB(db *gorm.DB) wrongRouteRecord {
	w.wrongRouteRecordDo.ReplaceDB(db)
	return w
}

type wrongRouteRecordDo struct{ gen.DO }

type IWrongRouteRecordDo interface {
	gen.SubQuery
	Debug() IWrongRouteRecordDo
	WithContext(ctx context.Context) IWrongRouteRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWrongRouteRecordDo
	WriteDB() IWrongRouteRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWrongRouteRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWrongRouteRecordDo
	Not(conds ...gen.Condition) IWrongRouteRecordDo
	Or(conds ...gen.Condition) IWrongRouteRecordDo
	Select(conds ...field.Expr) IWrongRouteRecordDo
	Where(conds ...gen.Condition) IWrongRouteRecordDo
	Order(conds ...field.Expr) IWrongRouteRecordDo
	Distinct(cols ...field.Expr) IWrongRouteRecordDo
	Omit(cols ...field.Expr) IWrongRouteRecordDo
	Join(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo
	Group(cols ...field.Expr) IWrongRouteRecordDo
	Having(conds ...gen.Condition) IWrongRouteRecordDo
	Limit(limit int) IWrongRouteRecordDo
	Offset(offset int) IWrongRouteRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWrongRouteRecordDo
	Unscoped() IWrongRouteRecordDo
	Create(values ...*model.WrongRouteRecord) error
	CreateInBatches(values []*model.WrongRouteRecord, batchSize int) error
	Save(values ...*model.WrongRouteRecord) error
	First() (*model.WrongRouteRecord, error)
	Take() (*model.WrongRouteRecord, error)
	Last() (*model.WrongRouteRecord, error)
	Find() ([]*model.WrongRouteRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WrongRouteRecord, err error)
	FindInBatches(result *[]*model.WrongRouteRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WrongRouteRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWrongRouteRecordDo
	Assign(attrs ...field.AssignExpr) IWrongRouteRecordDo
	Joins(fields ...field.RelationField) IWrongRouteRecordDo
	Preload(fields ...field.RelationField) IWrongRouteRecordDo
	FirstOrInit() (*model.WrongRouteRecord, error)
	FirstOrCreate() (*model.WrongRouteRecord, error)
	FindByPage(offset int, limit int) (result []*model.WrongRouteRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWrongRouteRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wrongRouteRecordDo) Debug() IWrongRouteRecordDo {
	return w.withDO(w.DO.Debug())
}

func (w wrongRouteRecordDo) WithContext(ctx context.Context) IWrongRouteRecordDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wrongRouteRecordDo) ReadDB() IWrongRouteRecordDo {
	return w.Clauses(dbresolver.Read)
}

func (w wrongRouteRecordDo) WriteDB() IWrongRouteRecordDo {
	return w.Clauses(dbresolver.Write)
}

func (w wrongRouteRecordDo) Session(config *gorm.Session) IWrongRouteRecordDo {
	return w.withDO(w.DO.Session(config))
}

func (w wrongRouteRecordDo) Clauses(conds ...clause.Expression) IWrongRouteRecordDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wrongRouteRecordDo) Returning(value interface{}, columns ...string) IWrongRouteRecordDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wrongRouteRecordDo) Not(conds ...gen.Condition) IWrongRouteRecordDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wrongRouteRecordDo) Or(conds ...gen.Condition) IWrongRouteRecordDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wrongRouteRecordDo) Select(conds ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wrongRouteRecordDo) Where(conds ...gen.Condition) IWrongRouteRecordDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wrongRouteRecordDo) Order(conds ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wrongRouteRecordDo) Distinct(cols ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wrongRouteRecordDo) Omit(cols ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wrongRouteRecordDo) Join(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wrongRouteRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wrongRouteRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wrongRouteRecordDo) Group(cols ...field.Expr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wrongRouteRecordDo) Having(conds ...gen.Condition) IWrongRouteRecordDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wrongRouteRecordDo) Limit(limit int) IWrongRouteRecordDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wrongRouteRecordDo) Offset(offset int) IWrongRouteRecordDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wrongRouteRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWrongRouteRecordDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wrongRouteRecordDo) Unscoped() IWrongRouteRecordDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wrongRouteRecordDo) Create(values ...*model.WrongRouteRecord) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wrongRouteRecordDo) CreateInBatches(values []*model.WrongRouteRecord, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wrongRouteRecordDo) Save(values ...*model.WrongRouteRecord) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wrongRouteRecordDo) First() (*model.WrongRouteRecord, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WrongRouteRecord), nil
	}
}

func (w wrongRouteRecordDo) Take() (*model.WrongRouteRecord, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WrongRouteRecord), nil
	}
}

func (w wrongRouteRecordDo) Last() (*model.WrongRouteRecord, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WrongRouteRecord), nil
	}
}

func (w wrongRouteRecordDo) Find() ([]*model.WrongRouteRecord, error) {
	result, err := w.DO.Find()
	return result.([]*model.WrongRouteRecord), err
}

func (w wrongRouteRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WrongRouteRecord, err error) {
	buf := make([]*model.WrongRouteRecord, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wrongRouteRecordDo) FindInBatches(result *[]*model.WrongRouteRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wrongRouteRecordDo) Attrs(attrs ...field.AssignExpr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wrongRouteRecordDo) Assign(attrs ...field.AssignExpr) IWrongRouteRecordDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wrongRouteRecordDo) Joins(fields ...field.RelationField) IWrongRouteRecordDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wrongRouteRecordDo) Preload(fields ...field.RelationField) IWrongRouteRecordDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wrongRouteRecordDo) FirstOrInit() (*model.WrongRouteRecord, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WrongRouteRecord), nil
	}
}

func (w wrongRouteRecordDo) FirstOrCreate() (*model.WrongRouteRecord, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WrongRouteRecord), nil
	}
}

func (w wrongRouteRecordDo) FindByPage(offset int, limit int) (result []*model.WrongRouteRecord, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wrongRouteRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wrongRouteRecordDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wrongRouteRecordDo) Delete(models ...*model.WrongRouteRecord) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wrongRouteRecordDo) withDO(do gen.Dao) *wrongRouteRecordDo {
	w.DO = *do.(*gen.DO)
	return w
}
