// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OpenID     string    `gorm:"column:open_id;comment:微信OpenID" json:"open_id"` // 微信OpenID
	Name       string    `gorm:"column:name" json:"name"`
	Account    string    `gorm:"column:account;not null" json:"account"`
	Password   string    `gorm:"column:password" json:"password"`
	Permission string    `gorm:"column:permission;not null;comment:权限级别(super最高权限,manager负责人权限,internal内部权限,external外部权限)" json:"permission"` // 权限级别(super最高权限,manager负责人权限,internal内部权限,external外部权限)
	PointName  string    `gorm:"column:point_name;comment:负责点位id" json:"point_name"`                                                          // 负责点位id
	Campus     string    `gorm:"column:campus;not null;comment:校区(zh朝晖,pf屏峰,mgs莫干山)" json:"campus"`                                           // 校区(zh朝晖,pf屏峰,mgs莫干山)
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
