// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotice = "notices"

// Notice mapped from table <notices>
type Notice struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64      `gorm:"column:user_id;not null;comment:接收通知的用户ID" json:"user_id"` // 接收通知的用户ID
	Type      NoticeType `gorm:"column:type;not null;comment:通知类型" json:"type"`            // 通知类型
	ActorID   *int64     `gorm:"column:actor_id;comment:发起操作的用户ID" json:"actor_id"`        // 发起操作的用户ID
	ActorName string     `gorm:"column:actor_name;comment:发起人姓名快照" json:"actor_name"`      // 发起人姓名快照
	TeamID    *int64     `gorm:"column:team_id;comment:相关队伍ID" json:"team_id"`             // 相关队伍ID
	ReadAt    *time.Time `gorm:"column:read_at;comment:确认时间，NULL表示未读" json:"read_at"`      // 确认时间，NULL表示未读
	CreatedAt time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName Notice's table name
func (*Notice) TableName() string {
	return TableNameNotice
}
