// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWrongRouteRecord = "wrong_route_records"

// WrongRouteRecord mapped from table <wrong_route_records>
type WrongRouteRecord struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TeamID         int64     `gorm:"column:team_id;not null;comment:队伍ID" json:"team_id"`                      // 队伍ID
	RouteName      string    `gorm:"column:route_name;not null;comment:原正确路线id如pf-half" json:"route_name"`     // 原正确路线id如pf-half
	WrongRouteName string    `gorm:"column:wrong_route_name;not null;comment:错走的路线id" json:"wrong_route_name"` // 错走的路线id
	AdminID        int64     `gorm:"column:admin_id;comment:记录该情况的管理员ID" json:"admin_id"`                      // 记录该情况的管理员ID
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
}

// TableName WrongRouteRecord's table name
func (*WrongRouteRecord) TableName() string {
	return TableNameWrongRouteRecord
}
