CREATE TABLE `teams` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '队伍ID',
  `name` varchar(64) NOT NULL COMMENT '队伍名称',
  `num` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '团队人数',
  `password` varchar(64) NOT NULL COMMENT '团队加入密码',
  `slogan` varchar(128) DEFAULT NULL COMMENT '团队标语',
  `allow_match` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否允许随机匹配',
  `captain` varchar(64) NOT NULL COMMENT '队长OpenID',
  `submit` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已提交报名',
  `route_name` varchar(64) DEFAULT NULL COMMENT '团队所属路线', 
  `prev_point_name` varchar(64) DEFAULT NULL COMMENT '上一经过点位ID',
  `status` varchar(64) NOT NULL  COMMENT '活动状态(notStart未出发，inProgress进行中，completed已完成，withdrawn已下撤)',
  `is_wrong_route` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否走错',
  `id_reunite` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否重组',
  `code` varchar(128) DEFAULT NULL COMMENT '签到二维码绑定码',
  `time` datetime(3) DEFAULT NULL COMMENT '队伍状态更新时间',
  `is_lost` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否失联',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_teams_code` (`code`),
  KEY `idx_teams_route_point` (`route_name`, `prev_point_name`),
  KEY `idx_teams_captain` (`captain`)
);