// Code generated by "gbc codegen". DO NOT EDIT.

//go:build !gbc_generate_exclude

package generate

import (
	"github.com/zjutjh/mygo/kit"
	"github.com/zjutjh/mygo/swagger"

	"app/comm"
)

func init() {
	// api/admin/authAdmin.go:103
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeAccountOrPasswordError,
			comm.CodeAdminLoginTooFrequently,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.authAdmin", statusCodes)
	}

	// api/admin/bindCode.go:187
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeTooFrequently,
			comm.CodeTeamFull,
			comm.CodeTeamNotEnough,
			comm.CodeTeamNotFound,
			comm.CodeBindCodeError,
			comm.CodeBindCodeDuplicated,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.bindCode", statusCodes)
	}

	// api/admin/confirmDestination.go:65
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.confirmDestination", statusCodes)
	}

	// api/admin/getTeamStatus.go:179
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeTeamNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.getTeamStatus", statusCodes)
	}

	// api/admin/getUserInfo.go:79
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
			comm.CodeUserNoQuota,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.getUserInfoByID", statusCodes)
	}

	// api/admin/logoutAdmin.go:37
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.logoutAdmin", statusCodes)
	}

	// api/admin/markTeamViolation.go:71
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeTeamNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.markTeamViolation", statusCodes)
	}

	// api/admin/markUserViolation.go:61
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.markUserViolation", statusCodes)
	}

	// api/admin/rebuildTeam.go:253
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
			comm.CodeTeamFull,
			comm.CodeTeamNotEnough,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.rebuild", statusCodes)
	}

	// api/admin/startPendingPeople.go:63
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.startPendingPeople", statusCodes)
	}

	// api/admin/updateTeam.go:427
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
			comm.CodeTooFrequently,
			comm.CodeNotInTeam,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeCampusMismatch,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.updateTeam", statusCodes)
	}

	// api/admin/updateUser.go:117
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
			comm.CodeTooFrequently,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.updateUser", statusCodes)
	}

	// api/dashboard/checkpoint.go:106
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard.hfCheckpoint", statusCodes)
	}

	// api/dashboard/overview.go:162
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard.hfOverview", statusCodes)
	}

	// api/dashboard/permission.go:53
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard.hfPermission", statusCodes)
	}

	// api/dashboard/segment.go:106
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard.hfSegment", statusCodes)
	}

	// api/dashboard/stats/all.go:184
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard/stats.hfAll", statusCodes)
	}

	// api/dashboard/stats/route.go:208
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard/stats.hfRoute", statusCodes)
	}

	// api/dashboard/teams/filter.go:209
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard/teams.hfFilter", statusCodes)
	}

	// api/dashboard/teams/lost.go:127
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
			comm.CodeTeamLostLocked,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard/teams.hfLost", statusCodes)
	}

	// api/dashboard/teams/team.go:158
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeDataNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/dashboard/teams.hfTeam", statusCodes)
	}

	// api/user/basic/login.go:84
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeAccountOrPasswordError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/basic.hfLogin", statusCodes)
	}

	// api/user/register/registerAlumnus.go:76
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyRegistered,
			comm.CodePeopleNotFound,
			comm.CodePeopleInfoWrong,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/register.hfRegisterAlumnus", statusCodes)
	}

	// api/user/register/registerStudent.go:170
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyRegistered,
			comm.CodeOAuthFailed,
			comm.CodeAccountOrPasswordError,
			comm.CodeNonStudentRegister,
			comm.CodePeopleInfoWrong,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/register.hfRegisterStudent", statusCodes)
	}

	// api/user/register/registerTeacher.go:89
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyRegistered,
			comm.CodeOAuthFailed,
			comm.CodeAccountOrPasswordError,
			comm.CodeNonTeacherRegister,
			comm.CodePeopleInfoWrong,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/register.hfRegisterTeacher", statusCodes)
	}

	// api/user/team/teamChangeCaptain.go:77
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamChangeCaptain", statusCodes)
	}

	// api/user/team/teamCreate.go:136
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyInTeam,
			comm.CodeNoCreateChance,
			comm.CodeTeamNameDuplicated,
			comm.CodePeopleNotFound,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamCreate", statusCodes)
	}

	// api/user/team/teamDetail.go:66
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeNotInTeam,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamDetail", statusCodes)
	}

	// api/user/team/teamDisband.go:63
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamDisband", statusCodes)
	}

	// api/user/team/teamJoin.go:90
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyInTeam,
			comm.CodeTeamFull,
			comm.CodeNoJoinChance,
			comm.CodeTeamSubmitted,
			comm.CodePasswordWrong,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeJoinTeamFailed,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamJoin", statusCodes)
	}

	// api/user/team/teamLeave.go:64
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeNotInTeam,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeCannotLeaveTeam,
			comm.CodeLeaveTeamFailed,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamLeave", statusCodes)
	}

	// api/user/team/teamMember.go:69
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeParameterInvalid,
			comm.CodeNotInTeam,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamMember", statusCodes)
	}

	// api/user/team/teamOverview.go:79
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeNotInTeam,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamOverview", statusCodes)
	}

	// api/user/team/teamRandomJoin.go:86
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyInTeam,
			comm.CodeTeamFull,
			comm.CodeNoJoinChance,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeJoinTeamFailed,
			comm.CodeTeamNotAllowMatch,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamRandomJoin", statusCodes)
	}

	// api/user/team/teamRandomList.go:78
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeParameterInvalid,
			comm.CodeNotFindTeams,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamRandomList", statusCodes)
	}

	// api/user/team/teamRemoveMember.go:85
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeCannotRemoveSelf,
			comm.CodeRemoveFailed,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamRemoveMember", statusCodes)
	}

	// api/user/team/teamRollback.go:64
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeTeamNotSubmitted,
			comm.CodeNotInRegisterTime,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
			comm.CodeAdjustmentCannotSubmit,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamRollback", statusCodes)
	}

	// api/user/team/teamSubmit.go:90
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNotEnough,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodeNotInRegisterTime,
			comm.CodeDailyQuotaFull,
			comm.CodeActivityQuotaFull,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
			comm.CodeAdjustmentCannotSubmit,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamSubmit", statusCodes)
	}

	// api/user/team/teamUpdate.go:94
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeNotInTeam,
			comm.CodeNotCaptain,
			comm.CodeTeamSubmitted,
			comm.CodeTeamNameDuplicated,
			comm.CodeTeamNotFound,
			comm.CodePeopleNotFound,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/team.hfTeamUpdate", statusCodes)
	}

	// api/user/user/userInfo.go:90
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePeopleNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/user.hfUserInfo", statusCodes)
	}

	// api/user/user/userModify.go:82
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
			comm.CodeParameterInvalid,
			comm.CodeAlreadyRegistered,
			comm.CodePeopleNotFound,
			comm.CodePreparationForbidden,
			comm.CodeActivityForbidden,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user/user.hfUserModify", statusCodes)
	}

	// middleware/checkPrem.go:29
	{
		statusCodes := []kit.Code{
			comm.CodeServerError,
			comm.CodeNotLoggedIn,
			comm.CodePermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/middleware.NeedPerm.func1", statusCodes)
	}
}
